# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_fifo_axi_0_0/fifo_design_fifo_axi_0_0.xci
# IP: The module: 'fifo_design_fifo_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/edit_fifo_axi_v1_0.srcs/constrs_1/new/fifo_design.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_design_fifo_axi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_fifo_axi_0_0/fifo_design_fifo_axi_0_0.xci
# IP: The module: 'fifo_design_fifo_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/edit_fifo_axi_v1_0.srcs/constrs_1/new/fifo_design.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_design_fifo_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
