# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_processing_system7_0_0/black_parrot_bd_1_processing_system7_0_0.xci
# IP: The module: 'black_parrot_bd_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_processing_system7_0_0/black_parrot_bd_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'black_parrot_bd_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_processing_system7_0_0/black_parrot_bd_1_processing_system7_0_0.xci
# IP: The module: 'black_parrot_bd_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_processing_system7_0_0/black_parrot_bd_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'black_parrot_bd_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
