# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fifo_design/fifo_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_design || ORIG_REF_NAME==fifo_design} -quiet] -quiet

# IP: bd/fifo_design/ip/fifo_design_processing_system7_0_0/fifo_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_design_processing_system7_0_0 || ORIG_REF_NAME==fifo_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/fifo_design/ip/fifo_design_fifo_axi_0_0/fifo_design_fifo_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_design_fifo_axi_0_0 || ORIG_REF_NAME==fifo_design_fifo_axi_0_0} -quiet] -quiet

# IP: bd/fifo_design/ip/fifo_design_smartconnect_0_0/fifo_design_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_design_smartconnect_0_0 || ORIG_REF_NAME==fifo_design_smartconnect_0_0} -quiet] -quiet

# IP: bd/fifo_design/ip/fifo_design_rst_ps7_0_50M_0/fifo_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==fifo_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/fifo_design/fifo_design_ooc.xdc
