# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/chaiwn/project_1_fifo_design/project_1_fifo_design.cache/wt [current_project]
set_property parent.project_path /home/chaiwn/project_1_fifo_design/project_1_fifo_design.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/chaiwn/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo /home/chaiwn/project_1_fifo_design/project_1_fifo_design.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs /home/chaiwn/ip_repo/basejump_stl/bsg_misc [current_fileset]
read_verilog /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/imports/bsg_misc/bsg_defines.v
set_property file_type "Verilog Header" [get_files /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/imports/bsg_misc/bsg_defines.v]
set_property is_global_include true [get_files /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/imports/bsg_misc/bsg_defines.v]
read_verilog -library xil_defaultlib /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/hdl/fifo_design_wrapper.v
add_files /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/fifo_design.bd
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_processing_system7_0_0/fifo_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/edit_fifo_axi_v1_0.srcs/constrs_1/new/fifo_design.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4d7f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4d7f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_5/bd_4d7f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_6/bd_4d7f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_7/bd_4d7f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_8/bd_4d7f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_9/bd_4d7f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_10/bd_4d7f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_11/bd_4d7f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_rst_ps7_0_50M_0/fifo_design_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_rst_ps7_0_50M_0/fifo_design_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_rst_ps7_0_50M_0/fifo_design_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/fifo_design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fifo_design_wrapper -part xc7z020clg400-1 -include_dirs /home/chaiwn/ip_repo/basejump_stl/bsg_misc/


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fifo_design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fifo_design_wrapper_utilization_synth.rpt -pb fifo_design_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
