# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.cache/wt [current_project]
set_property parent.project_path /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/fpga_build [current_project]
update_ip_catalog
set_property ip_output_repo /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/hdl/black_parrot_bd_1_wrapper.v
add_files /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/black_parrot_bd_1.bd
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_processing_system7_0_0/black_parrot_bd_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/bd_0/ip/ip_1/bd_1ecb_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/bd_0/ip/ip_1/bd_1ecb_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/bd_0/ip/ip_5/bd_1ecb_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/bd_0/ip/ip_6/bd_1ecb_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/bd_0/ip/ip_7/bd_1ecb_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/bd_0/ip/ip_8/bd_1ecb_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/bd_0/ip/ip_9/bd_1ecb_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/bd_0/ip/ip_10/bd_1ecb_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/bd_0/ip/ip_11/bd_1ecb_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/bd_0/ip/ip_1/bd_de9a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/bd_0/ip/ip_1/bd_de9a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/bd_0/ip/ip_5/bd_de9a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/bd_0/ip/ip_6/bd_de9a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/bd_0/ip/ip_7/bd_de9a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/bd_0/ip/ip_8/bd_de9a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/bd_0/ip/ip_9/bd_de9a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/bd_0/ip/ip_10/bd_de9a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/bd_0/ip/ip_11/bd_de9a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_proc_sys_reset_0_0/black_parrot_bd_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_proc_sys_reset_0_0/black_parrot_bd_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/ip/black_parrot_bd_1_proc_sys_reset_0_0/black_parrot_bd_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/chaiwn/zynq-parrot/cosim/black-parrot-example/fpga/black_parrot_bd_proj.srcs/sources_1/bd/black_parrot_bd_1/black_parrot_bd_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top black_parrot_bd_1_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef black_parrot_bd_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file black_parrot_bd_1_wrapper_utilization_synth.rpt -pb black_parrot_bd_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
