# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/black_parrot_bd_1/black_parrot_bd_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==black_parrot_bd_1 || ORIG_REF_NAME==black_parrot_bd_1} -quiet] -quiet

# IP: bd/black_parrot_bd_1/ip/black_parrot_bd_1_processing_system7_0_0/black_parrot_bd_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==black_parrot_bd_1_processing_system7_0_0 || ORIG_REF_NAME==black_parrot_bd_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/black_parrot_bd_1/ip/black_parrot_bd_1_top_0_0/black_parrot_bd_1_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==black_parrot_bd_1_top_0_0 || ORIG_REF_NAME==black_parrot_bd_1_top_0_0} -quiet] -quiet

# IP: bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_0_0/black_parrot_bd_1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==black_parrot_bd_1_smartconnect_0_0 || ORIG_REF_NAME==black_parrot_bd_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/black_parrot_bd_1/ip/black_parrot_bd_1_smartconnect_1_0/black_parrot_bd_1_smartconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==black_parrot_bd_1_smartconnect_1_0 || ORIG_REF_NAME==black_parrot_bd_1_smartconnect_1_0} -quiet] -quiet

# IP: bd/black_parrot_bd_1/ip/black_parrot_bd_1_proc_sys_reset_0_0/black_parrot_bd_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==black_parrot_bd_1_proc_sys_reset_0_0 || ORIG_REF_NAME==black_parrot_bd_1_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/black_parrot_bd_1/black_parrot_bd_1_ooc.xdc
