# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/chaiwn/ip_repo/edit_fifo_axi_v1_0.cache/wt [current_project]
set_property parent.project_path /home/chaiwn/ip_repo/edit_fifo_axi_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/chaiwn/ip_repo/fifo_axi_1.0
  /home/chaiwn/ip_repo/basejump_stl
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/chaiwn/ip_repo/edit_fifo_axi_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs /home/chaiwn/ip_repo/basejump_stl/bsg_misc [current_fileset]
read_verilog /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_defines.v
set_property file_type "Verilog Header" [get_files /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_defines.v]
set_property is_global_include true [get_files /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_defines.v]
read_verilog -library xil_defaultlib -sv {
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_circular_ptr.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_clkgate_optional.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_counter_up_down.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_dff_en.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_dlatch.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_fifo_1r1w_small.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_fifo_1r1w_small_hardened.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_fifo_1r1w_small_unhardened.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_fifo_tracker.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_flow_counter.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_mem_1r1w.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_mem_1r1w_sync.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_mem_1r1w_sync_synth.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_mem_1r1w_synth.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/src/bsg_two_fifo.v
}
read_verilog -library "" {
  /home/chaiwn/ip_repo/fifo_axi_1.0/hdl/fifo_axi_v1_0_S00_AXI.v
  /home/chaiwn/ip_repo/fifo_axi_1.0/hdl/fifo_axi_v1_0.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/chaiwn/ip_repo/edit_fifo_axi_v1_0.srcs/constrs_1/new/fifo_design.xdc
set_property used_in_implementation false [get_files /home/chaiwn/ip_repo/edit_fifo_axi_v1_0.srcs/constrs_1/new/fifo_design.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fifo_axi_v1_0 -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fifo_axi_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fifo_axi_v1_0_utilization_synth.rpt -pb fifo_axi_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
