# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/fifo_design_smartconnect_0_0.xci
# IP: The module: 'fifo_design_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/bd_4d7f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_0/bd_4d7f_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4d7f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_2/bd_4d7f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_3/bd_4d7f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_4/bd_4d7f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_5/bd_4d7f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_6/bd_4d7f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_7/bd_4d7f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_8/bd_4d7f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_9/bd_4d7f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_10/bd_4d7f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_11/bd_4d7f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_12/bd_4d7f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_design_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4d7f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4d7f_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_5/bd_4d7f_s00a2s_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_6/bd_4d7f_sarn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_7/bd_4d7f_srn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_8/bd_4d7f_sawn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_9/bd_4d7f_swn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_10/bd_4d7f_sbn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_11/bd_4d7f_m00s2a_0_ooc.xdc

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/fifo_design_smartconnect_0_0.xci
# IP: The module: 'fifo_design_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/bd_4d7f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_0/bd_4d7f_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4d7f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_2/bd_4d7f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_3/bd_4d7f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_4/bd_4d7f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_5/bd_4d7f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_6/bd_4d7f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_7/bd_4d7f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_8/bd_4d7f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_9/bd_4d7f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_10/bd_4d7f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_11/bd_4d7f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_12/bd_4d7f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_design_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4d7f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_1/bd_4d7f_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_5/bd_4d7f_s00a2s_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_6/bd_4d7f_sarn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_7/bd_4d7f_srn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_8/bd_4d7f_sawn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_9/bd_4d7f_swn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_10/bd_4d7f_sbn_0_ooc.xdc

# XDC: /home/chaiwn/project_1_fifo_design/project_1_fifo_design.srcs/sources_1/bd/fifo_design/ip/fifo_design_smartconnect_0_0/bd_0/ip/ip_11/bd_4d7f_m00s2a_0_ooc.xdc
